# Generated by Django 5.2.3 on 2025-06-28 00:51

import apps.common.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masson',
            options={'ordering': ['name'], 'verbose_name': 'Maçom', 'verbose_name_plural': 'Maçons'},
        ),
        migrations.AlterModelManagers(
            name='masson',
            managers=[
                ('active', apps.common.manager.ActiveBaseEntityManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='masson',
            name='description',
        ),
        migrations.AddField(
            model_name='masson',
            name='degree',
            field=models.CharField(choices=[('AM', 'Aprendiz'), ('CM', 'Companheiro'), ('MM', 'Mestre'), ('MI', 'Mestre Instalado')], default='AM', max_length=50, verbose_name='Grau'),
        ),
        migrations.AddField(
            model_name='masson',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='masson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
