# Generated by Django 5.2.3 on 2025-06-28 00:59

import apps.common.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('date', models.DateField(verbose_name='Data da Sessão')),
                ('degree', models.CharField(choices=[('AM', 'Aprendiz'), ('CM', 'Companheiro'), ('MM', 'Mestre'), ('MI', 'Mestre Instalado')], max_length=50, verbose_name='Grau')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['date'],
            },
            managers=[
                ('active', apps.common.manager.ActiveBaseEntityManager()),
            ],
        ),
    ]
