# Generated by Django 5.2.3 on 2025-06-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0001_initial'),
        ('massons', '0002_alter_masson_options_alter_masson_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='presents',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='massons.masson', verbose_name='Presentes'),
        ),
    ]
